language: "en_us"
new-player-max-playtime-seconds: 3600
code:
  length: 8
  characters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
rewards:
  playtime_1h:
    required-playtime-seconds: 3600
    display-name: "Invited player's playtime exceed one hour"
    commands:
      - "eco give %promoter% 1000"